sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
python:
  - "2.7"
cache:
  directories:
    - node_modules
env:
  global:
    - NODE_ENV=development
install:
  - npm install
  - sudo apt-get install python-pip python-dev
  - sudo pip install bs4
  - sudo pip install unirest
before_script:
  - npm run testrpc
script:
  - npm run truffle-test
  - npm run build-dev
  - npm run build-prod
after_script:
  - npm run solidity-coverage #Appena decidiamo che servizio usare lo pushamo sopra (coverall richiede il repo pubblico)
  - python sol-coverage.py -p #Push sul db metabase

