sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
notifications:
  email: false
  slack: 353swe:TBr27Dyzfxr9mmz1qYaWjJiv
cache:
  directories:
    - node_modules
env:
  global:
    - NODE_ENV=development
install:
  - npm install
script:
  - npm run build-prod
deploy:
  provider: surge
  project: ./build/
  domain: marvin.surge.sh
  on:
    all_branches: true

