language: node_js
node_js:
  - "6"

notifications:
  email: false
  slack: 353swe:TBr27Dyzfxr9mmz1qYaWjJiv

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build-dev
  - npm run build-prod
