sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
python:
  - "2.7"
notifications:
  email: false
  slack: 353swe:TBr27Dyzfxr9mmz1qYaWjJiv
cache:
  directories:
    - node_modules
env:
  global:
    - NODE_ENV=development
before_install:
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
after_failure: python scripts/travis/failed_build.py "$STAGE_NAME" "$TRAVIS_COMMIT_MESSAGE" "$TRAVIS_BRANCH" "$COMMITER_EMAIL"
jobs:
  include:
    - stage: test
      before_install: export STAGE_NAME=test
      install:
        - npm install
        - sudo pip install unirest
      before_script:
        - npm run testrpc
        - npm run compile
        - python scripts/travis/exec_and_report.py lint
      script:
        - python scripts/travis/exec_and_report.py test
    - stage: code-coverage
      if: branch = master
      before_install: export STAGE_NAME=coverage
      install:
        - sudo pip install unirest
        - sudo pip install bs4
      before_script: npm run rpcov
      script:
       - python scripts/coverage/js-coverage.py
       - python scripts/coverage/solidity-coverage.py
      after_success:
       - npm run merge-coverage
       - cat report.lcov | COVERALLS_REPO_TOKEN=$repo_token COVERALLS_SERVICE_NAME=travis-pro ./node_modules/.bin/coveralls
    - stage: deploy-to-production
      if: branch = master
      before_install: export STAGE_NAME=deploy
      script:
        - npm run build-prod
      deploy:
        provider: surge
        project: ./dist/
        domain: marvin.surge.sh
        skip_cleanup: true
