sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
python:
  - "2.7"
notifications:
  email: false
  slack: 353swe:TBr27Dyzfxr9mmz1qYaWjJiv
cache:
  directories:
    - node_modules
env:
  global:
    - NODE_ENV=development
before_install:
  - openssl aes-256-cbc -K $encrypted_25e5e99d9d5c_key -iv $encrypted_25e5e99d9d5c_iv -in .coveralls.yml.enc -out .coveralls.yml -d
install:
  - npm install
  - sudo apt-get install python-pip python-dev
  - sudo pip install bs4
  - sudo pip install unirest
before_script:
  - npm run testrpc
script:
  - npm run test
  - npm run truffle-test
  - npm run build-dev
  - npm run build-prod
after_script:
  - npm run make-coverage && npm run merge-coverage && npm run push-coverage

