@startuml
/'start custom theme'/
skinparam monochrome true
skinparam linetype ortho
skinparam componentStyle uml2
skinparam UsecaseBorderColor DarkGray
skinparam UsecaseBackgroundColor transparent

skinparam ActorBorderColor DarkGray
skinparam ActorBackgroundColor transparent
skinparam backgroundColor White

skinparam defaultFontName Arial
skinparam padding 1.3
/'end custom theme'/

rectangle UC5{
    (Gestione CRUD Lista Utenti sia prof che studenti) as UC5List
}
note right of UC5
UI Amministratore
end note
note right of (UC5List)
di queste liste indirizzo,nome,cognome,ruolo,corso
end note

/'hidden arrow to make UC6 under UC6'/
UC5 -[hidden]down- UC6

rectangle UC6{
    (Gestione CRUD Lista anno accademico)
}
note right of UC6
UI Universita
end note


UC6 -[hidden]down- UC7
rectangle UC7{
    (Gestione CRUD corsi Laurea)
    (Gestione CRUD esami di un corso)

    (Dettagli corso)
    (Dettagli esame)

    (Gestione prof -> esame)
}
note left of UC8
UI Amministratore
end note


rectangle UC8{
  (Lista esami)
  (Lista mie student)
  (Register exam evaluation)
  (Vedi codici esami)
  (Vedi corsi esami)
  (Vedi presenti exam)
}


UC7 -[hidden]down- UC8

note left of UC8
UI Prof
end note

UC8 -[hidden]down- UC9

rectangle UC9{
  (Lista suoi esami)
  (Add/See esami opzionali)
  (Crediti)
  (Valutazioni esami)
}
note right of UC9
UI Studente
end note

UC9 -[hidden]down- UC10
rectangle UC10{
    (CRUD amministratori)
}
note right of UC10
UI Amministratore
end note

@enduml


