@startuml

class UniversityBase{
- universityAddress addr
# registered map addr => bool
---
+ onlyFounder()
+ registrableAddress(addr)
---
UniversityBase()
+ isUniveristyFounder(addr):bool
+ login:uint
}

class UniversityAdmin{
- count admin:uint
# admins:map(addr => uint)
# adminsByIndex(uint => addr)
---
+ onlyAdmin()
+ validAdminAddress(addr)
---
+ isAdmin(addr):bool
+ getAdminsNumber():uint
+ getAdminAt(uint):addr
+ login:uint
}

UniversityBase <|-- UniversityAdmin


@enduml
